### ISSUE TITLE
URLs to posts require trailing slash

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/blog.reana.io#7]
This works: https://blog.reana.io/posts/2021/launching-reana-blog/

This does not: https://blog.reana.io/posts/2021/launching-reana-blog

It is very well possible that one may omit the trailing slash, so it would be good to make both URLs work.

**Comment by mvidalgarcia** [comment]
I'm currently investigating it... It seems to be due to [nginx config listening on port 8080](https://github.com/reanahub/blog.reana.io/blob/936e984ab55e46e05c40236e6c934815d22e0e0c/nginx.conf#L2).
Hugo performs a redirect (301) when accessing a blog post without a trailing slash, but in our case, it tries to redirect to `blog.reana.io:8080` because is the port being listened to.

![image](https://user-images.githubusercontent.com/8863238/110125151-4b477100-7dc3-11eb-9520-37d123bee896.png)
